- name: SELinuxの状態確認
  command:
    /usr/sbin/selinuxenabled
  register:
    result
  changed_when: false
  failed_when: result.rc not in [0, 1]

- name: 起動時にSELinux無効化 (/etc/sysconfig/selinux)
  become: yes
  selinux: state=disabled
  when: result.rc == 0

- name: SELinux無効化 (setenforce)
  become: yes
  command: setenforce 0
  when: result.rc == 0

- name: firewalldが起動しているか確認
  become: yes
  shell: firewall-cmd --state
  register: firewall_state
  ignore_errors: yes
  changed_when: false
  check_mode: no

- name: firewalldでHTTPを許可
  become: yes
  command: firewall-cmd --zone=public --add-service=http --permanent
  when: firewall_state.rc == 0

- name: firewalldのポリシーをリロード
  become: yes
  command: firewall-cmd --reload
  when: firewall_state.rc == 0

- name: 開発ツールのインストール
  become: yes
  yum: name='@Development Tools'

- name: RubyとPassengerのビルドに必要な開発ツールやヘッダファイルのインストール
  become: yes
  yum:
    name='openssl-devel,readline-devel,zlib-devel,curl-devel,libyaml-devel,libffi-devel'

- name:  PostgreSQLとヘッダファイルのインストール
  become: yes
  yum:
    name='postgresql-server,postgresql-devel,python-psycopg2'

- name: Apacheとヘッダファイルのインストール
  become: yes
  yum:
    name='httpd,httpd-devel'

- name: ImageMagickとヘッダファイル・日本語フォントのインストール
  become: yes
  yum:
    name='ImageMagick,ImageMagick-devel,ipa-pgothic-fonts'

- name: そのほかのツールのインストール
  become: yes
  yum:
    name='subversion,git,which'

- name: 作業ディレクトリ作成
  file: path={{ work_dir }}
    state=directory
    mode=0755
