production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: "localhost"
      port: 25
      domain: "{{ ansible_fqdn }}"

  rmagick_font_path: /usr/share/fonts/ipa-pgothic/ipagp.ttf
